/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: MessageBase.proto */

/* Do not generate deprecated warnings for self */
#ifndef PROTOBUF_C__NO_DEPRECATED
#define PROTOBUF_C__NO_DEPRECATED
#endif

#include "MessageBase.pb-c.h"
void   sub1__init
                     (Sub1         *message)
{
  static const Sub1 init_value = SUB1__INIT;
  *message = init_value;
}
size_t sub1__get_packed_size
                     (const Sub1 *message)
{
  assert(message->base.descriptor == &sub1__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t sub1__pack
                     (const Sub1 *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &sub1__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t sub1__pack_to_buffer
                     (const Sub1 *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &sub1__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Sub1 *
       sub1__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Sub1 *)
     protobuf_c_message_unpack (&sub1__descriptor,
                                allocator, len, data);
}
void   sub1__free_unpacked
                     (Sub1 *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &sub1__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
void   base__init
                     (Base         *message)
{
  static const Base init_value = BASE__INIT;
  *message = init_value;
}
size_t base__get_packed_size
                     (const Base *message)
{
  assert(message->base.descriptor == &base__descriptor);
  return protobuf_c_message_get_packed_size ((const ProtobufCMessage*)(message));
}
size_t base__pack
                     (const Base *message,
                      uint8_t       *out)
{
  assert(message->base.descriptor == &base__descriptor);
  return protobuf_c_message_pack ((const ProtobufCMessage*)message, out);
}
size_t base__pack_to_buffer
                     (const Base *message,
                      ProtobufCBuffer *buffer)
{
  assert(message->base.descriptor == &base__descriptor);
  return protobuf_c_message_pack_to_buffer ((const ProtobufCMessage*)message, buffer);
}
Base *
       base__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data)
{
  return (Base *)
     protobuf_c_message_unpack (&base__descriptor,
                                allocator, len, data);
}
void   base__free_unpacked
                     (Base *message,
                      ProtobufCAllocator *allocator)
{
  if(!message)
    return;
  assert(message->base.descriptor == &base__descriptor);
  protobuf_c_message_free_unpacked ((ProtobufCMessage*)message, allocator);
}
static const ProtobufCFieldDescriptor sub1__field_descriptors[1] =
{
  {
    "sub_a",
    1,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Sub1, has_sub_a),
    offsetof(Sub1, sub_a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned sub1__field_indices_by_name[] = {
  0,   /* field[0] = sub_a */
};
static const ProtobufCIntRange sub1__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 1 }
};
const ProtobufCMessageDescriptor sub1__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Sub1",
  "Sub1",
  "Sub1",
  "",
  sizeof(Sub1),
  1,
  sub1__field_descriptors,
  sub1__field_indices_by_name,
  1,  sub1__number_ranges,
  (ProtobufCMessageInit) sub1__init,
  NULL,NULL,NULL    /* reserved[123] */
};
static const ProtobufCFieldDescriptor base__field_descriptors[3] =
{
  {
    "base_a",
    1,
    PROTOBUF_C_LABEL_REQUIRED,
    PROTOBUF_C_TYPE_INT32,
    0,   /* quantifier_offset */
    offsetof(Base, base_a),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_b",
    2,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_INT32,
    offsetof(Base, has_base_b),
    offsetof(Base, base_b),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
  {
    "base_c",
    3,
    PROTOBUF_C_LABEL_OPTIONAL,
    PROTOBUF_C_TYPE_BYTES,
    offsetof(Base, has_base_c),
    offsetof(Base, base_c),
    NULL,
    NULL,
    0,             /* flags */
    0,NULL,NULL    /* reserved1,reserved2, etc */
  },
};
static const unsigned base__field_indices_by_name[] = {
  0,   /* field[0] = base_a */
  1,   /* field[1] = base_b */
  2,   /* field[2] = base_c */
};
static const ProtobufCIntRange base__number_ranges[1 + 1] =
{
  { 1, 0 },
  { 0, 3 }
};
const ProtobufCMessageDescriptor base__descriptor =
{
  PROTOBUF_C__MESSAGE_DESCRIPTOR_MAGIC,
  "Base",
  "Base",
  "Base",
  "",
  sizeof(Base),
  3,
  base__field_descriptors,
  base__field_indices_by_name,
  1,  base__number_ranges,
  (ProtobufCMessageInit) base__init,
  NULL,NULL,NULL    /* reserved[123] */
};
